container/deps/vllm/data_plane/data_plane.py
examples/hello_world/client/client.py
examples/hello_world/operators/encoder_decoder.py
examples/hello_world/single_file.py
icp/src/python/triton_distributed/icp/data_plane.py
icp/src/python/triton_distributed/icp/nats_request_plane.py
icp/src/python/triton_distributed/icp/request_plane.py
icp/src/python/triton_distributed/icp/ucp_data_plane.py
icp/tests/python/test_data_plane.py
icp/tests/python/test_request_plane.py
pyproject.toml
worker/src/python/triton_distributed/worker/deployment.py
worker/src/python/triton_distributed/worker/operator.py
worker/src/python/triton_distributed/worker/remote_operator.py
worker/src/python/triton_distributed/worker/remote_request.py
worker/src/python/triton_distributed/worker/remote_response.py
worker/src/python/triton_distributed/worker/remote_tensor.py
worker/src/python/triton_distributed/worker/triton_core_operator.py
worker/src/python/triton_distributed/worker/worker.py
worker/tests/python/conftest.py
worker/tests/python/integration/api_server/models/mock_disaggregated_serving/1/model.py
worker/tests/python/integration/operators/add_multiply_divide.py
worker/tests/python/integration/operators/identity.py
worker/tests/python/integration/operators/mock_disaggregated_serving.py
worker/tests/python/integration/test_add_multiply_divide.py
worker/tests/python/integration/test_direct.py
worker/tests/python/integration/test_mock_disaggregated_serving.py
worker/tests/python/integration/test_perf_benchmark.py
worker/tests/python/unit/test_args.py
worker/tests/python/unit/test_logger.py

add triton_distributed to isort know_first_party list

build: update isort known first party config

---

examples/hello_world/deploy/__main__.py

fix: encoder repetition typo

---

README.md

Add Release badge that displays latest release tag and points to latest release notes

Add Release badge to README page

---

examples/llm/api_server/__main__.py
examples/llm/vllm/deploy/parser.py
worker/src/python/triton_distributed/worker/__init__.py
worker/src/python/triton_distributed/worker/deployment.py
worker/src/python/triton_distributed/worker/logger.py
worker/src/python/triton_distributed/worker/remote_response.py
worker/src/python/triton_distributed/worker/triton_core_operator.py
worker/src/python/triton_distributed/worker/worker.py
worker/tests/python/conftest.py
worker/tests/python/integration/operators/add_multiply_divide.py
worker/tests/python/integration/operators/identity.py
worker/tests/python/integration/operators/mock_disaggregated_serving.py
worker/tests/python/integration/operators/triton_core_models/postprocessing/1/model.py
worker/tests/python/integration/operators/triton_core_models/preprocessing/1/model.py
worker/tests/python/integration/test_add_multiply_divide.py
worker/tests/python/integration/test_consolidated_logging.py
worker/tests/python/integration/test_direct.py
worker/tests/python/integration/test_mock_disaggregated_serving.py
worker/tests/python/integration/test_perf_benchmark.py
worker/tests/python/unit/test_logger.py

Improve the logging interface for the worker. 
Relies on FileHandler to write to the given file.
Consolidate logs into a single file instead of 3 different files.
Improve the error reporting for the tasks when nats is closed by providing our own exception handler.

refactor: Improve the usage of logging in worker

---

container/Dockerfile
examples/llm/api_server/chat_vllm.py
examples/llm/api_server/remote_model_connector.py
examples/llm/tensorrtllm/deploy/__main__.py
examples/llm/tensorrtllm/operators/disaggregated_serving.py
examples/llm/tensorrtllm/operators/triton_core_models/mock/1/model.py
examples/llm/tensorrtllm/operators/triton_core_models/mock/config.pbtxt
examples/llm/tensorrtllm/operators/triton_core_models/simple_postprocessing/1/model.py
examples/llm/tensorrtllm/operators/triton_core_models/simple_postprocessing/config.pbtxt
examples/llm/tensorrtllm/operators/triton_core_models/simple_preprocessing/1/model.py
examples/llm/tensorrtllm/operators/triton_core_models/simple_preprocessing/config.pbtxt
examples/llm/tensorrtllm/scripts/known_models.py

Nnshah1 trtllm disag

---

examples/llm/api_server/__main__.py
examples/llm/api_server/chat_tensorrtllm.py
examples/llm/api_server/parser.py
examples/llm/api_server/remote_model_connector.py
examples/llm/api_server/triton_distributed_engine.py
examples/llm/tensorrtllm/deploy/__main__.py
examples/llm/tensorrtllm/deploy/parser.py
examples/llm/tensorrtllm/operators/triton_core_models/mock/config.pbtxt

feat(llm): Add example of aggregated TRTLLM

---

examples/llm/tensorrtllm/deploy/launch_workers.py

- [Separate disagg_model_workflow out from mpiexec process](https://github.com/triton-inference-server/triton_distributed/commit/ddd6433f7e83b56508e5d17845c995d2c1197298)

fix: Separate disaggregated serving workflow model out from mpiexec process

---

container/build.sh
examples/llm/vllm/benchmark/README.md

vllm readme updates

---

examples/llm/tensorrtllm/operators/disaggregated_serving.py

refactor: Replace trtllm example prints with debug logs

---

.github/workflows/pre-merge-rust.yml
runtime/rust/LICENSE
runtime/rust/deny.toml

adds deny.toml to check for permissive licenses in rust dependencies
I also added the License to the rust directory. If we are going to publish a crate, then it needs to have the license attached to it. Also the cargo-deny check will fail without the License file copied there as well. 

add deny.toml, update CI to run license checks

---

README.md

docs: updating

---

applications/llm/bin/tio/Cargo.lock
llm/rust/Cargo.lock
llm/rust/triton-llm/Cargo.toml
llm/rust/triton-llm/src/engines/mistralrs.rs

fix: Unique IDs for mistralrs requests

---

icp/python/src/triton_distributed/icp/nats_event_plane.py
icp/tests/python/event_plane/test_publish_subscribe.py

Small tweak to make subscribe and publish take the same arguments for defining event topic.

fix: updating subscribe and publish to take same args for event topic

---

runtime/rust/src/component.rs
runtime/rust/src/component/endpoint.rs
runtime/rust/src/lib.rs

Simple addition of facades/traits for Runtime and DistributedRuntime on objects that propagate them.

refactor: adding facades for runtimes

---

container/deps/vllm/vllm_v0.7.2.patch

Enhance vLLM patch with WAR for deepseek architecture support in KC connector from @IzzyPutterman .

feat: disaggregation support for deepseek arch models

---

container/Dockerfile

- Remove duplicate venv setup
- Rearrange layers to reduce rebuilds of certain layers that don't change often

fix: Remove duplicate venv setup in Dockerfile

---

container/Dockerfile.vllm

Updates Docker.vllm to include KV Routing changes.
- [x ] fix

refactor: Move vLLM KV Routing changes to Dockerfile.vllm

---

examples/rust/Cargo.lock
runtime/rust/Cargo.lock
triton.code-workspace

- update dependencies
- fix update triton.code-workspace with new paths

fix: triton.code-workpace; update dependencies

---

llm/rust/Cargo.lock
runtime/rust/Cargo.lock
runtime/rust/Cargo.toml
runtime/rust/src/config.rs
runtime/rust/src/worker.rs

This PR adds unit tests to confirm env vars override defaults for worker and blocking threads count on `RuntimeConfig`.
- closes GitHub issue: #146

test: add unit tests for RuntimeConfig

---

.github/workflows/docs_update_ci.yml
CODEOWNERS

Trigger Workflow only when documentation is updated
- Leave a comment on the PR that documentation will skip CI
- Repository admin needs to verify changes and approve + merge such PRs and force merge the PR

Create docs wokflow

---

examples/python_rs/llm/tensorrt_llm/README.md

chore: add instructions to build env

---

examples/python_rs/llm/vllm/kv_router/worker.py

Initialize engine before runtime
- [ x] fix

[fix] initialize vLLM engine before runtime

---

container/deps/vllm/vllm_v0.7.2-triton-kv-disagg-patch.patch
examples/python_rs/llm/vllm/kv_router/router.py
examples/python_rs/llm/vllm/kv_router/worker.py
llm/rust/triton-llm/src/kv_router/scheduler.rs

feat: enable metrics reporting in vllm/kv_router example. Update vLLM patch

---

runtime/rust/src/component/namespace.rs
runtime/rust/src/component/service.rs
runtime/rust/src/lib.rs
runtime/rust/src/logging.rs
runtime/rust/src/runtime.rs
runtime/rust/src/worker.rs

enables #[tokio::test] via `Runtime::from_current()`
This uses the current handle as both the primary and secondary.

fix: simplifying the ability to test using from_current

---

runtime/rust/src/utils/stream.rs

- Minor update to DeadlineStream
- Adding tests

refactor: adding tests and simplifying DeadlineStream

---

runtime/rust/src/transports/etcd.rs

- adds etcd method to atomic create or validate a kv entry.
- adds integration tests to validate the behavior

feat: adding etcd method kv_create_or_validate

---

triton.code-workspace

Update code workspace directories after restructure

chore: Update code workspace directories after restructure

---

README.md
lib/bindings/python/README.md
lib/runtime/README.md

chore: updating docs after restructure

---

applications/llm/count/Cargo.lock
examples/rust/Cargo.lock
launch/tio/Cargo.lock
launch/tio/Cargo.toml
launch/tio/README.md
launch/tio/src/lib.rs
launch/tio/src/main.rs
launch/tio/src/net.rs
launch/tio/src/opt.rs
lib/bindings/c/Cargo.lock
lib/bindings/python/Cargo.lock
lib/llm/Cargo.lock
lib/llm/Cargo.toml
lib/llm/src/engines.rs
lib/llm/src/engines/sglang.rs
lib/llm/src/engines/sglang/engine.rs
lib/llm/src/engines/sglang/subprocess.rs
lib/llm/src/engines/sglang/worker.rs

- Setup venv
```
uv venv
source .venv/bin/activate
uv pip install pip
uv pip install sgl-kernel --force-reinstall --no-deps
uv pip install "sglang[all]==0.4.2" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer/
```
- Build: `cargo build --release --features sglang`
- Run single node (make sure you're in the venv): `./tio out=sglang ~/llm_models/my_model`
- Run Deepseek multi-gpu / multi-node:
Node 1:
```
tio in=http out=sglang --model-path ~/llm_models/DeepSeek-R1-Distill-Llama-70B/ --tensor-parallel-size 8 --num-nodes 2 --node-rank 0 --dist-init-addr 10.217.98.122:9876
```
Node 2:
```
tio in=none out=sglang --model-path ~/llm_models/DeepSeek-R1-Distill-Llama-70B/ --tensor-parallel-size 8 --num-nodes 2 --node-rank 1 --dist-init-addr 10.217.98.122:9876
```

feat: sglang backend for tio

---

container/deps/vllm/vllm_v0.7.2-triton-kv-disagg-patch.patch

fix: Add TritonNcclConnector back to vllm patch

---

.github/workflows/pre-merge-rust.yml
applications/llm/count/Cargo.toml
deny.toml
launch/tio/Cargo.toml

* add licenses and run cargo deny for all

ci: fix rust deny workflow

---

container/Dockerfile.vllm_nixl

Update the Dockerfile.vllm_nixl with changes from Dockerfile.vllm

Update wheel build in Dockerfile.vllm_nixl

---

lib/llm/src/protocols/openai/chat_completions.rs

fix: add skip_serializing if none
TBD
`lib/llm/src/protocols/openai/chat_completions.rs`
TBD

fix: add skip_serializing if none

---

launch/tio/Cargo.lock
launch/tio/Cargo.toml
launch/tio/README.md
launch/tio/src/lib.rs
launch/tio/src/main.rs
launch/tio/src/opt.rs
lib/llm/Cargo.lock
lib/llm/Cargo.toml
lib/llm/src/engines.rs
lib/llm/src/engines/llamacpp.rs
lib/llm/src/engines/mistralrs.rs

feat: llama.cpp engine for tio

---

container/Dockerfile
deploy/Kubernetes/_build/tester.containerfile
deploy/docker-compose.yml
examples/python_rs/llm/tensorrt_llm/common/parser.py
examples/python_rs/llm/tensorrt_llm/disaggregated/llmapi_disaggregated_configs/single_node_config.yaml
examples/python_rs/llm/tensorrt_llm/disaggregated/worker.py

Updates to support DS R1 in TRTLLM example

---

examples/__init__.py
examples/python_rs/__init__.py
examples/python_rs/llm/__init__.py
examples/python_rs/llm/tensorrt_llm/__init__.py

Fix for: 
https://github.com/triton-inference-server/triton_distributed/issues/306

Add missing inits

---

launch/tio/Cargo.toml
launch/tio/README.md
launch/tio/src/lib.rs
launch/tio/src/main.rs
launch/tio/src/opt.rs
lib/llm/Cargo.toml
lib/llm/src/engines.rs
lib/llm/src/engines/vllm.rs
lib/llm/src/engines/vllm/engine.rs
lib/llm/src/engines/vllm/subprocess.rs
lib/llm/src/engines/vllm/worker.rs

triton-distributed-llm component and support in tio

feat: vllm engine
