container/build.sh, examples/llm/vllm/README.md
Changes:
- Update VERSION in build.sh to reflect the latest v0.1.1 release in the image tag when building an image locally.
- Add section to README on how to cleanup processes between deployments to avoid collisions or a messy state between runs.
=> chore: Update build version to v0.1.1 and add Teardown section to LLM example README

examples/llm/api_server/chat.py, examples/llm/api_server/remote_model_connector.py, examples/llm/tensorrtllm/README.md, examples/llm/tensorrtllm/deploy/launch_workers.py
Fixes
- Fix launch of disaggregated_serving model in launch_workers script (typo in command after removing it from mpiexec)
- Add flushing of store_dir
- Fix string/numpy array handling in API server
Remaining work:
- IMPORTANT: Document / automate using that env var `export TRTLLM_USE_MPI_KVCACHE=1` (not in current code, added manually in shell)
- IMPORTANT: Cleanup FIXMEs and CUDA_VISIBLE_DEVICES / device setting logic (make sure when running the example that context/generate engines are loaded on separate GPUs)
=> fix: Fix disaggregated TRTLLM inference

ATTRIBUTIONS.md, runtime/rust/ATTRIBUTIONS-Rust.md
Added Rust attributions. See: https://github.com/triton-inference-server/triton_distributed/blob/dtokarev/rust-libs-attributions/runtime/rust/ATTRIBUTIONS-Rust.md
=> Added runtime/rust/ATTRIBUTIONS-Rust.md

container/build.sh
Adds fallback logic to set `latest_tag=0.0.1` if git tags aren't found for whatever reason, which would previously lead to an error with the SCM version during pip install:
```
fatal: No names found, cannot describe anything.
...
PYTHON_PACKAGE_VERSION=.dev+6c62884
...
packaging.version.InvalidVersion: Invalid version: '.dev+6c62884'
```
=> fix: Set default 'latest' tag if git tags fail to get parsed

.github/workflows/pre-merge-rust.yml
Fixes failures like this: https://github.com/triton-inference-server/triton_distributed/actions/runs/13171148554/workflow
``` 
GitHub Actions
/ .github/workflows/pre-merge-rust.yml
Invalid workflow file
you may only define one of `paths` and `paths-ignore` for a single event
```
Shouldn't need to exclude kubernetes directory changes here since it is already specific to changes made in rust directory
=> ci: Remove conflicting paths-ignore from rust action

.github/workflows/trigger_ci_pull.yml, .github/workflows/trigger_ci_push.yml
This change adds filters to both pull and push automation scripts that limit when work will sent to the NVIDIA Test Lab based on the target branch of and paths modified by a pull request.
This should help prevent unnecessary work from being sent to lab machines.
=> ci: restrict which branches & paths trigging lab testing

runtime/rust/src/component.rs, runtime/rust/src/discovery.rs, runtime/rust/src/pipeline/context.rs, runtime/rust/src/pipeline/network.rs, runtime/rust/src/pipeline/network/tcp/server.rs, runtime/rust/src/pipeline/nodes.rs, runtime/rust/src/runtime.rs, runtime/rust/src/worker.rs
`cargo doc` now runs without warnings.
=> doc: Fix doc links

runtime/tests/python/integration/test_mock_disaggregated_serving.py, runtime/tests/python/integration/test_perf_benchmark.py
Marks slower mock_disagg and perf_benchmark tests to nightly instead of pre_merge.
This should cut down pytest time from ~5-10min to ~1-2min.
Corresponding gitlab PR to run nightly tests coming soon.
=> ci: Move slow pytests to nightly

container/Dockerfile, container/build.sh, container/deps/requirements.txt
Moving to latest release of Triton 25.01.
=> chore: Update base from from 24.12 to 25.01 Triton version

llm/rust/rust-toolchain.toml, runtime/rust/examples/hello_world/Cargo.lock, runtime/rust/examples/hello_world/rust-toolchain.toml, runtime/rust/python-wheel/rust-toolchain.toml, runtime/rust/rust-toolchain.toml
A repeat of https://github.com/triton-inference-server/triton_distributed/pull/145 that was accidentally reverted in https://github.com/triton-inference-server/triton_distributed/pull/123
=> chore: Again: Add rust-toolchain so we're all on the same version

runtime/rust/python-wheel/rust/engine.rs, runtime/rust/python-wheel/rust/lib.rs, runtime/rust/src/component.rs, runtime/rust/src/component/client.rs, runtime/rust/src/component/endpoint.rs, runtime/rust/src/component/service.rs, runtime/rust/src/lib.rs, runtime/rust/src/pipeline/network/egress/push.rs, runtime/rust/src/pipeline/network/ingress/push_endpoint.rs, runtime/rust/src/pipeline/network/tcp/client.rs, runtime/rust/src/runtime.rs, runtime/rust/src/service.rs, runtime/rust/src/transports/etcd.rs, runtime/rust/src/transports/etcd/lease.rs, runtime/rust/src/transports/nats.rs, runtime/rust/src/worker.rs
Previously we pretended it was the `log` crate, but they have subtly different interfaces. See https://github.com/triton-inference-server/triton_distributed/issues/154
=> refactor: Use tracing crate

runtime/rust/python-wheel/rust/lib.rs, runtime/rust/src/config.rs, runtime/rust/src/pipeline/network.rs, runtime/rust/src/pipeline/network/egress/push.rs, runtime/rust/src/pipeline/network/ingress/push_handler.rs, runtime/rust/src/pipeline/network/tcp/client.rs, runtime/rust/src/pipeline/network/tcp/server.rs
Replace `unwrap()` with error handling at the interface between JSON and Rust; where weak typing becomes strong typing.
=> refactor: Handle JSON serialize / de-serialize errors.

.github/workflows/pre-merge-rust.yml, .gitignore
Rust pre-merge check on source code for `tio` moved from `apps/tio` to `applications/llm/bin/tio` - so updating the check accordingly.
Should fix this error: https://github.com/triton-inference-server/triton_distributed/actions/runs/13318456550/job/37198020744
=> fix: Fix rust pre-merge for new tio directory

.github/workflows/copyright-check.ps1, applications/llm/bin/tio/Cargo.lock, applications/llm/bin/tio/Cargo.toml, applications/llm/bin/tio/README.md, applications/llm/bin/tio/src/lib.rs, applications/llm/bin/tio/src/main.rs, applications/llm/bin/tio/src/opt.rs, llm/rust/Cargo.lock, llm/rust/triton-llm/Cargo.toml, llm/rust/triton-llm/src/engines.rs, llm/rust/triton-llm/src/engines/mistralrs.rs
This allows us to run a real model.
Build:
```
cargo build --release --features mistralrs,cuda
```
Run:
```
./target/release/tio in=text out=mistralrs --model-path Llama-3.2-1B-Instruct-Q4_K_M.gguf
```
Why [mistral.rs](https://github.com/EricLBuehler/mistral.rs)?
- It has no dependencies. You don't need a container or a virtual env to get started.
- It supports CUDA, Metal (MacOS) and CPU-only. Everyone can join the AI revolution.
- It starts fast and serves fast (with CUDA). That makes it fun to experiment with.
- It runs many models, not just Mistral, that's just it's name.
The key file is `llm/rust/triton-llm/src/engines/mistralrs.rs`. The other changes are small.
=> feat: Add a mistralrs engine to tio

applications/llm/bin/tio/src/main.rs
Previously `tio` wouldn't run unless etcd and nats were present in the environment, even though it doesn't use them yet.
This makes it easier to use `tio`.
=> bug: tio can run without NATS or ETCD

.gitignore, applications/llm/bin/tio/README.md, applications/llm/bin/tio/src/lib.rs, applications/llm/bin/tio/src/main.rs, llm/rust/triton-llm/src/engines/mistralrs.rs, llm/rust/triton-llm/src/kv_router.rs, llm/rust/triton-llm/src/kv_router/scheduler.rs
You can now run an HF repo directly:
```
tio ~/llm_models/Llama-3.2-1B-Instruct/
```
or a GGUF
```
tio ~/llm_models/Llama-3.2-1B-Instruct-Q4_K_M.gguf
```
Also cleanup kv_router so I can merge.
=> feat(tio): Defaults for in and out, support HF repos

CODEOWNERS
We are bottle-necked on Rust code review. Expand.
=> ci: Add Biswa and Thomas as Rust reviewers

applications/llm/tio/src/input/endpoint.rs, applications/llm/tio/src/input/http.rs, applications/llm/tio/src/input/text.rs, applications/llm/tio/src/lib.rs, applications/llm/tio/src/opt.rs, applications/llm/tio/src/output.rs, applications/llm/tio/src/output/echo_core.rs, lib/llm/src/model_card/create.rs, lib/llm/tests/preprocessor.rs
Add backend type `EngineConfig::StaticCore` that wraps the engine in a preprocessor (prompt templating and tokenization).
Add example engine `echo_core` (`out=echo_core`) which takes and returns tokens. A nice side effect is that it echos the full prompt template with system prompt, whereas `echo_full` echos only user prompt.
=> feat: tio support preprocessor

.gitignore, applications/llm/tio/src/input/endpoint.rs, applications/llm/tio/src/lib.rs, lib/runtime/src/pipeline/error.rs, lib/runtime/src/protocols.rs
Adds `TryFrom<&str>` and `FromStr` for `Endpoint` as well as docs and tests.
Why? Refactors a bit. Documentation and tests are always good. But mainly want to make sure I have permissions to land a PR.
#235 
`applications/llm/tio/src/input/endpoint.rs`
- Unit tests were added
- E2E tests not relevant
TBD
N/A
Feedback in #235 
Related to #235
=> refactor: adds `TryFrom<&str>` and `FromStr` for `Endpoint`

lib/runtime/src/protocols.rs
This means we don't need to explain the parts to the users until they are ready. We use what they provide and default the rest.
Allows all of this and more:
- `tio out=tdr://test`
- `tio out=tdr://llama_8b_pool`
- `tio in=tdr://corp_ai_research_group/model_next-20250226`
- `tio out=tdr://AIRE.NIM.migrate.mistralrs.1802`
Python, API, etc all untouched.
=> feat: Endpoint defaults for namespace/component/other

applications/llm/count/src/main.rs
Follow-up from https://github.com/triton-inference-server/triton_distributed/pull/280#discussion_r1972408608
=> refactor: Move arg parsing into app for cleaner signatures

.gitattributes
Remove the strange `Roff` section from the language repo stats by excluding the test/data files from [Linguist](https://github.com/github-linguist/linguist/tree/main) detection: https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
=> chore: Remove 'Roff' section from repo language stats

launch/tio/src/input/endpoint.rs, launch/tio/src/input/http.rs, launch/tio/src/input/text.rs, launch/tio/src/lib.rs, launch/tio/src/output/echo_full.rs, lib/llm/src/http/service/discovery.rs, lib/llm/src/http/service/openai.rs, lib/llm/src/preprocessor.rs, lib/llm/src/preprocessor/prompt/template/oai.rs, lib/llm/src/protocols/openai/chat_completions.rs, lib/llm/src/protocols/openai/chat_completions/delta.rs, lib/llm/src/types.rs, lib/llm/tests/http-service.rs, lib/llm/tests/preprocessor.rs
Rename `ChatCompletionRequest` to `NvCreateChatCompletionRequest`.
```rust
// previously ChatCompletionRequest
#[derive(Serialize, Deserialize, Validate, Debug, Clone)]
pub struct NvCreateChatCompletionRequest {
#[serde(flatten)]
pub inner: async_openai::types::CreateChatCompletionRequest,
pub nvext: Option<NvExt>,
}
```
https://github.com/triton-inference-server/triton_distributed/pull/261
`lib/llm/protocols/openai/chat_completions.rs`
No tests added. Global search-and-replace.
N/A
https://github.com/triton-inference-server/triton_distributed/pull/261#issuecomment-2686039733
- closes GitHub issue: #283
=> refactor: rename ChatCompletionRequest to NvCreateChatCompletionRequest

launch/tio/src/input/endpoint.rs, launch/tio/src/input/http.rs, launch/tio/src/input/text.rs, launch/tio/src/lib.rs, launch/tio/src/output/echo_full.rs, lib/llm/src/engines/mistralrs.rs, lib/llm/src/http/service/discovery.rs, lib/llm/src/preprocessor.rs, lib/llm/src/protocols/codec.rs, lib/llm/src/protocols/openai/chat_completions.rs, lib/llm/src/protocols/openai/chat_completions/aggregator.rs, lib/llm/src/protocols/openai/chat_completions/delta.rs, lib/llm/src/types.rs, lib/llm/tests/http-service.rs
Rename `ChatCompletionResponseDelta` to `NvCreateChatCompletionStreamResponse`.
```rust
// previously ChatCompletionResponseDelta
#[derive(Serialize, Deserialize, Validate, Debug, Clone)]
pub struct NvCreateChatCompletionStreamResponse {
#[serde(flatten)]
pub inner: async_openai::types::CreateChatCompletionStreamResponse,
}
```
https://github.com/triton-inference-server/triton_distributed/pull/261
`lib/llm/protocols/openai/chat_completions.rs`
No tests added. Global search-and-replace.
N/A
https://github.com/triton-inference-server/triton_distributed/pull/261#issuecomment-2686039733
- closes GitHub issue: #283
=> refactor: rename ChatCompletionResponseDelta to NvCreateChatCompletionStreamResponse

lib/llm/src/protocols/openai/chat_completions.rs, lib/llm/src/protocols/openai/chat_completions/aggregator.rs, lib/llm/src/protocols/openai/chat_completions/delta.rs
Removes wrapper for `ChatCompletionContent` and adds documentation to all `openai::chat_completions::*`.
https://github.com/triton-inference-server/triton_distributed/pull/261
`lib/llm/protocols/openai/chat_completions.rs`
No tests added. Global search-and-replace.
N/A
https://github.com/triton-inference-server/triton_distributed/pull/261#issuecomment-2686039733
- closes GitHub issue: #283
=> refactor: removes wrapper for ChatCompletionContent and adds documentation

examples/python_rs/llm/vllm/kv_router/router.py, examples/python_rs/llm/vllm/kv_router/worker.py, lib/bindings/python/rust/llm/kv.rs, lib/llm/src/kv_router.rs, lib/llm/src/kv_router/publisher.rs, lib/llm/src/kv_router/scheduler.rs
This https://github.com/triton-inference-server/triton_distributed/pull/282 change caused the KV Routing example to break. This fixes those problems
- Only run .service_builder().create() once for a given endpoint
- handle the case where metrics are sent from endpoints without metrics_handlers and the data field is null
- [ x] fix
=> [fix] KV Router Example fixes 

applications/llm/count/visualization/docker-compose.yml, applications/llm/count/visualization/grafana.json
Changes:
- Tweak grafana defaults for more to be more ergonomic for quickstart and local testing
- ref on min refresh interval: https://github.com/grafana/grafana/issues/710#issuecomment-1913545694
- Remove unused docker volumes to simplify docker-compose.yml
Example usage:
```
cd applications/llm/count/visualization
docker compose up -d
cd applications/llm/count
TRD_LOG=info cargo run --bin count -- --namespace triton-init --component vllm --endpoint load_metrics
cd examples/python_rs/llm/vllm
./scripts/kv-router-run.sh 2 prefix deepseek-ai/DeepSeek-R1-Distill-Llama-8B
```
=> chore: Tweak prometheus/grafana config defaults

container/Dockerfile.vllm_nixl
See https://github.com/triton-inference-server/triton_distributed/pull/325/files#r1976746070
Before:
```bash
ModuleNotFoundError: No module named 'nixl_bindings'
```
After:
```bash
./container/build.sh --framework vllm_nixl --build-context nixl=/home/rmccormick/triton/distributed/nixl
./container/build.sh --framework vllm_nixl --build-context nixl=/home/rmccormick/triton/distributed/nixl --target dev
./container/run.sh --framework vllm_nixl -it --hf-cache ~/.cache/huggingface -- python -c "import nixl_bindings"
./container/run.sh --framework vllm_nixl -it --hf-cache ~/.cache/huggingface --target dev -- python -c "import nixl_bindings"
```
=> fix: Fix nixl install / PYTHONPATH in both dev and runtime targets

.github/workflows/pre-merge-rust.yml, container/Dockerfile, container/Dockerfile.vllm, container/Dockerfile.vllm_nixl, launch/tio/rust-toolchain.toml, lib/bindings/python/rust-toolchain.toml, lib/llm/rust-toolchain.toml, lib/runtime/rust-toolchain.toml
`cargo build --locked` won't let you use "1.85.0" if you only have "stable" installed, even if those are the same thing right now.
=> fix: Install specific toolchain
